# Generated by Django 5.2.7 on 2025-11-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_optimizer', '0002_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='demand_forecast',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
